server:
  port: 9200
spring:
  datasource:
    url: jdbc:mysql://localhost/rides?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
users:
  admin:
    username: uberadmin
    password: uberadmin
    authorities: ROLE_ADMIN
  app:
    username: uberapp
    password: uberapp
    authorities: ROLE_APP